use_frameworks!

target 'WLEmptyState_Example' do
  pod 'WLEmptyState', :path => '../'

  target 'WLEmptyState_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
