use_frameworks!
platform :ios, '13.0'

target 'WLEmptyState_Example' do
  pod 'WLEmptyState', :path => '../'

  target 'WLEmptyState_Tests' do
    inherit! :search_paths

    pod 'iOSSnapshotTestCase'
  end
end
