name: "WLEmptyState CI"
uses: ty0x2333/cocoapods-action@0.2.0

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@main
    - name: Set xcode Version
      run: sudo xcode-select -s /Applications/Xcode_11.5.app
    - name: Install Dependencies
      run: |
        cd Example
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.5'
        additional_lint_params: --private
